# Generated by Django 3.1 on 2021-07-18 12:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pages', '0002_customuser_uniquename'),
    ]

    operations = [
        migrations.AddField(
            model_name='createscribe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
