# Generated by Django 3.1 on 2021-08-04 10:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210723_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createscribe',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
